runtime: nodejs18

env_variables:
  DB_HOST: ${DB_HOST}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_NAME: ${DB_NAME}
  JWT_SECRET: ${JWT_SECRET}

service: default

instance_class: F2

handlers:
  - url: /static
    static_dir: static/
  - url: /.* 
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 3

entrypoint: npm start